"""add_atr_and_market_regime_filters

Revision ID: 19918569ac5d
Revises: d25c9c70b586
Create Date: 2026-01-13 23:03:55.190324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19918569ac5d'
down_revision: Union[str, Sequence[str], None] = 'd25c9c70b586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_configs', sa.Column('atr_period', sa.Integer(), nullable=True))
    op.add_column('strategy_configs', sa.Column('atr_multiplier', sa.Float(), nullable=True))
    op.add_column('strategy_configs', sa.Column('market_regime_enabled', sa.Boolean(), nullable=True))
    op.add_column('strategy_configs', sa.Column('adx_period', sa.Integer(), nullable=True))
    op.add_column('strategy_configs', sa.Column('adx_threshold', sa.Float(), nullable=True))
    op.add_column('strategy_configs', sa.Column('max_volatility_multiplier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_configs', 'max_volatility_multiplier')
    op.drop_column('strategy_configs', 'adx_threshold')
    op.drop_column('strategy_configs', 'adx_period')
    op.drop_column('strategy_configs', 'market_regime_enabled')
    op.drop_column('strategy_configs', 'atr_multiplier')
    op.drop_column('strategy_configs', 'atr_period')
    # ### end Alembic commands ###
