"""add_signal_quality_fields

Revision ID: 40a3a63e03d2
Revises: 20260114230000
Create Date: 2026-01-16 20:09:05.986852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a3a63e03d2'
down_revision: Union[str, Sequence[str], None] = '20260114230000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('signal_strength', sa.Float(), nullable=True))
    op.add_column('signals', sa.Column('value_zone', sa.String(length=20), nullable=True))
    op.add_column('signals', sa.Column('signal_reason', sa.String(length=255), nullable=True))
    op.add_column('signals', sa.Column('is_absorption', sa.Boolean(), nullable=True))
    op.add_column('signals', sa.Column('cvd_momentum', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_strategy_configs_strategy_type'), table_name='strategy_configs')
    op.create_index(op.f('ix_strategy_configs_strategy_type'), 'strategy_configs', ['strategy_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_configs_strategy_type'), table_name='strategy_configs')
    op.create_index(op.f('idx_strategy_configs_strategy_type'), 'strategy_configs', ['strategy_type'], unique=False)
    op.drop_column('signals', 'cvd_momentum')
    op.drop_column('signals', 'is_absorption')
    op.drop_column('signals', 'signal_reason')
    op.drop_column('signals', 'value_zone')
    op.drop_column('signals', 'signal_strength')
    # ### end Alembic commands ###
