"""Initial schema

Revision ID: 727635da6783
Revises: 
Create Date: 2026-01-12 15:49:12.696375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727635da6783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backteststatus'), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('take_profit_pct', sa.Float(), nullable=True),
    sa.Column('trailing_stop_activation', sa.Float(), nullable=True),
    sa.Column('trailing_stop_distance', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('annualized_return_pct', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('num_buy_trades', sa.Integer(), nullable=True),
    sa.Column('num_sell_trades', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_capital', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backtest_runs_created_at', 'backtest_runs', ['created_at'], unique=False)
    op.create_index('idx_backtest_runs_status', 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_name'), 'backtest_runs', ['name'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_data_symbol_timeframe', 'market_data', ['symbol', 'timeframe'], unique=False)
    op.create_index('idx_market_data_symbol_timestamp', 'market_data', ['symbol', 'timestamp'], unique=False)
    op.create_index('idx_market_data_timestamp', 'market_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', 'HOLD', name='signaltype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('rsi_value', sa.Float(), nullable=True),
    sa.Column('ma_fast', sa.Float(), nullable=True),
    sa.Column('ma_slow', sa.Float(), nullable=True),
    sa.Column('trend_sma', sa.Float(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_backtest_run_id', 'signals', ['backtest_run_id'], unique=False)
    op.create_index('idx_signals_signal_type', 'signals', ['signal_type'], unique=False)
    op.create_index('idx_signals_timestamp', 'signals', ['timestamp'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('fast_period', sa.Integer(), nullable=False),
    sa.Column('slow_period', sa.Integer(), nullable=False),
    sa.Column('use_ema', sa.Boolean(), nullable=False),
    sa.Column('rsi_period', sa.Integer(), nullable=True),
    sa.Column('rsi_overbought', sa.Float(), nullable=True),
    sa.Column('rsi_oversold', sa.Float(), nullable=True),
    sa.Column('trend_filter_period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_run_id')
    )
    op.create_index(op.f('ix_strategy_configs_id'), 'strategy_configs', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.Enum('LONG', 'SHORT', name='tradetype'), nullable=False),
    sa.Column('precio_entrada', sa.Float(), nullable=False),
    sa.Column('precio_salida', sa.Float(), nullable=False),
    sa.Column('pnl_dollar', sa.Float(), nullable=False),
    sa.Column('pnl_percent', sa.Float(), nullable=False),
    sa.Column('capital_final', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.Enum('STOP_LOSS', 'TAKE_PROFIT', 'TRAILING_STOP', 'SIGNAL', name='exitreason'), nullable=True),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_backtest_run_id', 'trades', ['backtest_run_id'], unique=False)
    op.create_index('idx_trades_fecha_entrada', 'trades', ['fecha_entrada'], unique=False)
    op.create_index('idx_trades_tipo', 'trades', ['tipo'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index('idx_trades_tipo', table_name='trades')
    op.drop_index('idx_trades_fecha_entrada', table_name='trades')
    op.drop_index('idx_trades_backtest_run_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_strategy_configs_id'), table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index('idx_signals_timestamp', table_name='signals')
    op.drop_index('idx_signals_signal_type', table_name='signals')
    op.drop_index('idx_signals_backtest_run_id', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index('idx_market_data_timestamp', table_name='market_data')
    op.drop_index('idx_market_data_symbol_timestamp', table_name='market_data')
    op.drop_index('idx_market_data_symbol_timeframe', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_backtest_runs_name'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_index('idx_backtest_runs_status', table_name='backtest_runs')
    op.drop_index('idx_backtest_runs_created_at', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
