"""add_volume_filters

Revision ID: d25c9c70b586
Revises: 727635da6783
Create Date: 2026-01-12 19:58:21.392368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25c9c70b586'
down_revision: Union[str, Sequence[str], None] = '727635da6783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('volume_reversal_period', sa.Integer(), nullable=True))
    op.add_column('backtest_runs', sa.Column('volume_reversal_threshold', sa.Float(), nullable=True))
    op.add_column('strategy_configs', sa.Column('volume_period', sa.Integer(), nullable=True))
    op.add_column('strategy_configs', sa.Column('volume_ratio_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_configs', 'volume_ratio_threshold')
    op.drop_column('strategy_configs', 'volume_period')
    op.drop_column('backtest_runs', 'volume_reversal_threshold')
    op.drop_column('backtest_runs', 'volume_reversal_period')
    # ### end Alembic commands ###
